### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by kovacbb** [muhammadidrees/bloc_rest_api#1]
Hi, thanks for the nice plugin.
Does it also support web, as I did not saw it on pub description?

**Comment by muhammadidrees** [comment]
Hello @kovacbb,
Thanks for opening an issue.

**Yes, the package has web support.**

The issue in pub scoring arises due to the package's dependency on `HydratedBloc` and its dependency on `path_provider` which is currently not supported by the web (refer to [issue](https://github.com/flutter/flutter/issues/45296#issue-526261064)). But `HydratedBloc` itself has web support (refer to [issue](https://github.com/felangel/bloc/issues/1548#issue-668052573)). So you can use the package with no issues.

I'll make sure to add this in the pub description as well in a couple of days.

Hope this clarifies your concern. Cheers! :relaxed:
